/* config.h. Generated by cmake from config.h.cmake */

#ifndef TAGLIB_CONFIG_H
#define TAGLIB_CONFIG_H

/* Indicates the byte order of your target system */
/* 1 if little-endian, 2 if big-endian. */
#cmakedefine   SYSTEM_BYTEORDER ${SYSTEM_BYTEORDER}

/* Size of floating point types */
#cmakedefine   SIZEOF_FLOAT      ${SIZEOF_FLOAT}
#cmakedefine   SIZEOF_DOUBLE     ${SIZEOF_DOUBLE}
#cmakedefine   SIZEOF_LONGDOUBLE ${SIZEOF_LONGDOUBLE}

/* Defined if your compiler supports some byte swap functions */
#cmakedefine   HAVE_GCC_BYTESWAP_16 1
#cmakedefine   HAVE_GCC_BYTESWAP_32 1
#cmakedefine   HAVE_GCC_BYTESWAP_64 1
#cmakedefine   HAVE_GLIBC_BYTESWAP 1
#cmakedefine   HAVE_MSC_BYTESWAP 1
#cmakedefine   HAVE_MAC_BYTESWAP 1
#cmakedefine   HAVE_OPENBSD_BYTESWAP 1

/* Defined if your compiler supports shared_ptr */
#cmakedefine   HAVE_CXX11_SMART_PTR 1
#cmakedefine   HAVE_BOOST_SMART_PTR 1

/* Defined if your compiler supports some atomic operations */
#cmakedefine   HAVE_GCC_ATOMIC 1
#cmakedefine   HAVE_MAC_ATOMIC 1
#cmakedefine   HAVE_WIN_ATOMIC 1
#cmakedefine   HAVE_IA64_ATOMIC 1

/* Defined if your compiler supports snpritf or sprintf_s. */
#cmakedefine   HAVE_SNPRINTF 1
#cmakedefine   HAVE_SPRINTF_S 1

/* Defined if your compiler supports ISO _strdup. */
#cmakedefine   HAVE_ISO_STRDUP 1

/* Defined if your compiler supports codecvt */
#cmakedefine   HAVE_STD_CODECVT 1

/* Defined if you have libz */
#cmakedefine   HAVE_ZLIB 1

/* Indicates whether debug messages are shown even in release mode */
#cmakedefine   TRACE_IN_RELEASE 1

#cmakedefine TESTS_DIR "@TESTS_DIR@"

#endif  // TAGLIB_CONFIG_H
