/* config.h. Generated by cmake from config.h.cmake */

#ifndef TAGLIB_CONFIG_H
#define TAGLIB_CONFIG_H

/* Defined if your compiler supports some byte swap functions */
#cmakedefine   HAVE_GCC_BYTESWAP 1
#cmakedefine   HAVE_GLIBC_BYTESWAP 1
#cmakedefine   HAVE_MSC_BYTESWAP 1
#cmakedefine   HAVE_MAC_BYTESWAP 1
#cmakedefine   HAVE_OPENBSD_BYTESWAP 1

/* Defined if your compiler supports ISO _strdup */
#cmakedefine   HAVE_ISO_STRDUP 1

/* Defined if zlib is installed */
#cmakedefine   HAVE_ZLIB 1

/* Indicates whether debug messages are shown even in release mode */
#cmakedefine   TRACE_IN_RELEASE 1

#cmakedefine TESTS_DIR "@TESTS_DIR@"

#cmakedefine WITH_APE 1
#cmakedefine WITH_ASF 1
#cmakedefine WITH_DSF 1
#cmakedefine WITH_MOD 1
#cmakedefine WITH_MP4 1
#cmakedefine WITH_RIFF 1
#cmakedefine WITH_SHORTEN 1
#cmakedefine WITH_TRUEAUDIO 1
#cmakedefine WITH_VORBIS 1

#endif
